### ISSUE TITLE
DNSSD packet parsing failed - HassOS - RPi4

### ISSUE THREAD

**Issue by oscarsiles** [home-assistant-libs/python-matter-server#323] opened 2023-06-12 11:12 UTC
I'm having the same issue mentioned in #307, with the addon-on logs repeating:
```
2023-06-12 12:03:01 core-matter-server chip.DIS[126] ERROR DNSSD packet parsing failed (for SRV records)
2023-06-12 12:03:01 core-matter-server chip.DIS[126] ERROR DNSSD packet parsing failed (for non-srv records)
```

I have HassOS 10.2 installed on a baremetal Raspberry Pi 4, with IPv6 enabled (obtaining the correct addresses on ethernet). Checking sysctl, the values of `accept_ra` and `accept_ra_rt_info_max_plen` are both 0 and cannot be changed.

**Comment by marcelveldt** [comment] 2023-06-19 09:20
@agners any insights ? Is this related to certain network settings ?

@oscarsiles do you have a multicast dns repeater active in your network ?

**Comment by oscarsiles** [comment] 2023-06-19 12:54
No, I double checked on my router and it is disabled. Should it be enabled?

**Comment by marcelveldt** [comment] 2023-06-19 13:01
No, please don't as it causes tons of issues.
So I assume you have a flat network, without any VLANs etc ?

Do you perhaps have Unifi network gear ?

**Comment by agners** [comment] 2023-06-19 13:10
The add-on parses all mDNS/DNS-SD messages which it captures (it joins the mDNS multicast). Since mDNS/DNS-SD is widely used technology, it is likely that this is caused by some other (non-Matter) device.

Do you have issues with the Matter add-on which you attribute to this errors?

What would be interesting is to have a network/wireshark capture to see the exact packet which causes it (and what it's source is). It might trigger a mDNS implementation bug or it indeed is just a device which sends out broken mDNS/DNS-SD packets. If it is the latter, as long as its not a Matter device, that shouldn't be a problem really.

**Comment by oscarsiles** [comment] 2023-06-19 13:11
No VLANs or unifi gear; it's a pretty generic network.

**Comment by agners** [comment] 2023-06-19 13:15
> Checking sysctl, the values of `accept_ra` and `accept_ra_rt_info_max_plen` are both 0 and cannot be changed.

FWIW, that is correct for HAOS as we use NetworkManager's RA implementation.

**Comment by planbnet** [comment] 2023-06-20 09:45
> Do you perhaps have Unifi network gear ?

I have the same problem and I am indeed using a Unifi Dream Router and several APs. Do you have an idea what might be causing this and how to fix it in this case?

**Comment by marcelveldt** [comment] 2023-06-22 08:34
> I have the same problem and I am indeed using a Unifi Dream Router and several APs. Do you have an idea what might be causing this and how to fix it in this case?

For Unifi hardware (and probably others too) you need to make sure that you do not enable it's mDNS forwarding feature as it messes with the discovery packets. Even if you do not use any VLAN's make sure that option is disabled.

Secondly my personal experience was that enabling "multicast enhancements" on the WifI networks also caused stability issues, like devices going unavailable at random times or just unable to be discovered at all. As Matter and Thread are both very new, it will take time until router and firewall applications are optimized for their traffic.

**Comment by marcelveldt** [comment] 2023-06-27 09:27
@oscarsiles did you discover which device on your network was broadcasting the (malformed) data ?
Can we close this issue ?

**Comment by planbnet** [comment] 2023-06-27 09:34
Disabling mDNS forwarding in my Unifi router solved the problem for me.
However, shouldn't the logging be relaxed? It makes no sense to log errors that are caused by unrelated other devices with such a high frequency.

**Comment by marcelveldt** [comment] 2023-06-27 09:37
Well, lowering the logging hides the issue so I'm not a fan of that. Better solve the issue instead of hiding it.

**Comment by oscarsiles** [comment] 2023-06-27 09:46
I finally figured out what was causing it - disabling this addon stopped the messages: https://github.com/hassio-addons/addon-aircast . I toggled it on/off a few times and that would restart the error messages.

**Comment by marcelveldt** [comment] 2023-06-29 12:17
Ah, thanks for reporting it back, that will help others

**Closed** 2023-07-11 10:36 UTC
Labels: mdns

**Comment by 1bobby-git** [comment] 2024-02-16 01:50
same issue

**Comment by akzov** [comment] 2024-03-30 16:38
Bonjour protocol is such a nightmare to deal with. If only we could just specify the IP address to connect to.

**Comment by rwjack** [comment] 2026-04-06 17:02
**resolved - scroll down**

I don't have the aircast addon installed, but I do get the exact same errors, a whole load of them:

```
2026-04-06 18:59:44.604 (Dummy-2) CHIP_ERROR [chip.native.DIS] DNSSD packet parsing failed (for SRV records)
2026-04-06 18:59:44.604 (Dummy-2) CHIP_ERROR [chip.native.DIS] DNSSD packet parsing failed (for non-srv records)
```

The errors stop when I disable this in pfsense avahi settings:

<img width="1135" height="74" alt="Image" src="https://github.com/user-attachments/assets/53fed3f9-c1bd-4595-a27d-6d1c79266ff0" />

BUT, that also breaks my spotifyPlus/librespot setup.

When repeating is enabled, my HA instance can resolve the local dns name for a HA local addon, and spotifyPlus works

```
➜  ~ dig local-snapcast-server-libspot.local

; <<>> DiG 9.20.19 <<>> local-snapcast-server-libspot.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26504
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 611d1563af86289a (echoed)
;; QUESTION SECTION:
;local-snapcast-server-libspot.local. IN	A

;; ANSWER SECTION:
local-snapcast-server-libspot.local. 60	IN A	172.30.32.1 # add-on container ip
local-snapcast-server-libspot.local. 60	IN A	172.30.232.1 # unclear - probably some other docker local network
local-snapcast-server-libspot.local. 60	IN A	192.168.1.9 # ha interface 3
local-snapcast-server-libspot.local. 60	IN A	172.16.9.9 # ha interface 2
local-snapcast-server-libspot.local. 60	IN A	10.1.100.9 # ha interface 1

;; Query time: 4 msec
;; SERVER: 172.30.32.3#53(172.30.32.3) (UDP)
;; WHEN: Mon Apr 06 18:58:51 CEST 2026
;; MSG SIZE  rcvd: 331
```

---

When repeating is disabled, it flat out fails (which breaks the spotifyPlus intergration):

```
➜  ~ dig local-snapcast-server-libspot.local

; <<>> DiG 9.20.19 <<>> local-snapcast-server-libspot.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4373
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: c11381fdcbe77bda (echoed)
;; QUESTION SECTION:
;local-snapcast-server-libspot.local. IN	A

;; Query time: 7625 msec
;; SERVER: 172.30.32.3#53(172.30.32.3) (UDP)
;; WHEN: Mon Apr 06 15:25:35 CEST 2026
;; MSG SIZE  rcvd: 76
```

Can someone help me get to the bottom of this?

---

Update: I configured `--zeroconf-interface=<single-ha-ip>` as a librespot parameter, and I don't get any more errors, even with mdns reflection enabled.
