### ISSUE TITLE
Add the ability to share matter devices with other controllers/apps

### ISSUE THREAD

**Issue by ArturoGuerra** [home-assistant-libs/python-matter-server#220] opened 2023-02-28 00:22 UTC

**Comment by ArturoGuerra** [comment] 2023-02-28 08:22
Looking at the code that puts a device in commissioning mode doesn't actually return a paring code and when trying to do it directly using the latest chip library it always seems to stall.

**Comment by marcelveldt** [comment] 2023-04-17 09:44
duplicate of #205

**Closed by marcelveldt** 2023-04-17 09:44 UTC
