### ISSUE TITLE
Issue with running the latest stable Docker image

### ISSUE THREAD

**Issue by denisvitez** [home-assistant-libs/python-matter-server#710] opened 2024-05-18 11:20 UTC
Hello,
I have tried running the latest stable Docker image, and I'm getting the following error inside my container:
`2024-05-18 11:11:36.204 (MainThread) ERROR [matter_server.server] Error doing task: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/server.py", line 145, in start
    await self.device_controller.initialize(self.paa_root_cert_dir)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 130, in initialize
    await fetch_certificates(paa_root_cert_dir)
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 209, in fetch_certificates
    last_fetch = await loop.run_in_executor(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 206, in _check_paa_root_dir
    paa_root_cert_dir.mkdir()
  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.11/site-packages/credentials/development/paa-root-certs'`

I am running the image with the following command from the Readme:
`docker run -d \
  --name matter-server \
  --restart=unless-stopped \
  --security-opt apparmor=unconfined \
  -v $(pwd)/data:/data \
  -v /run/dbus:/run/dbus:ro \
  --network=host \
  ghcr.io/home-assistant-libs/python-matter-server:stable`

If I revert back to the version 5.10, it works:

`docker run -d \
  --name matter-server \
  --restart=unless-stopped \
  --security-opt apparmor=unconfined \
  -v $(pwd)/data:/data \
  -v /run/dbus:/run/dbus:ro \
  --network=host \
  ghcr.io/home-assistant-libs/python-matter-server:5.10`

**Comment by udoersam** [comment] 2024-05-19 07:11
Same problem here. Just did a downgrade to version 5.10.0 and the matter-server works again.
Just as a workaround.

**Comment by apreick** [comment] 2024-05-19 08:42
It's the same for me
python-matter-server:stable => 6.0 does not work
python-matter-server:5.10 works 

System:

```
Client: Docker Engine - Community
 Version:    26.1.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Kernel Version: 6.6.30-v8-16k+
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
```

**Comment by fadelguy** [comment] 2024-05-19 17:39
Same here
python-matter-server:stable => 6.0 does not work
python-matter-server:5.10 works

**Comment by simmac** [comment] 2024-05-20 11:10
Duplicate of #704 . It's already fixed in main, but there hasn't been a release for the docker image. There are a few workarounds in #704 for the meantime.

**Comment by marcelveldt** [comment] 2024-05-20 14:56
6.0.1 has been released with bugfixes for the docker image.

**Closed by marcelveldt** 2024-05-20 14:56 UTC
