### ISSUE TITLE
Repository 1.0.6 not available in HACS

### ISSUE THREAD

**Issue by roessi** [home-assistant-libs/python-matter-server#121] opened 2022-12-01 17:10 UTC
hi,
don't know if it a bug but HACS don't accept 1.0.6.
got the message
<Integration home-assistant-libs/python-matter-server> Repository structure for 1.0.6 is not compliant

thx Rudi

**Comment by frenck** [comment] 2022-12-01 17:11
Duplicate of #113

Please, check if your issue was already reported before creating a new one.

Thanks! 👍 

../Frenck

**Closed by frenck** 2022-12-01 17:11 UTC

**Comment by roessi** [comment] 2022-12-01 17:13
Sorry 🙈

Rudi

Am 01.12.2022 um 18:11 schrieb Franck Nijhof ***@***.***>:

﻿

Duplicate of #113<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhome-assistant-libs%2Fpython-matter-server%2Fissues%2F113&data=05%7C01%7C%7Cc7f9792e7a5b4e0ccd1808dad3bf1f2e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638055115052476739%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oqxxflZxJO5qCs3ZxW6lWslgXjcjpRepvBIZnp%2BvQC8%3D&reserved=0>

Please, check if your issue was already reported before creating a new one.

Thanks! 👍

../Frenck
