### ISSUE TITLE
Timeout errors after turning off Matter device

### ISSUE THREAD

**Issue by testuser7** [home-assistant-libs/python-matter-server#403] opened 2023-10-03 12:56 UTC
After turning off Matter device (bulb) I have many timeout errors in logs.
Is this okay? Is there any way to disable logging of such errors?
```
2023-10-03 07:28:17 NAS chip.DMG[1] ERROR Subscription Liveness timeout with SubscriptionID = 0x1f18eb3f, Peer = 01:0000000000000002
2023-10-03 07:28:17 NAS matter_server.server.device_controller.[node 2][1] INFO Previous subscription failed with Error: 50, re-subscribing in 0 ms...
2023-10-03 07:28:48 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 07:29:02 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 07:29:02 NAS chip.DMG[1] ERROR Failed to establish CASE for re-subscription with error 'src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout'
2023-10-03 07:29:02 NAS matter_server.server.device_controller.[node 2][1] INFO Previous subscription failed with Error: 50, re-subscribing in 7669 ms...
2023-10-03 07:29:40 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 07:29:54 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 07:29:54 NAS chip.DMG[1] ERROR Failed to establish CASE for re-subscription with error 'src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout'
2023-10-03 07:29:54 NAS matter_server.server.device_controller.[node 2][1] INFO Previous subscription failed with Error: 50, re-subscribing in 8388 ms...
2023-10-03 07:30:33 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 07:30:47 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 07:30:47 NAS chip.DMG[1] ERROR Failed to establish CASE for re-subscription with error 'src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout'
2023-10-03 07:30:47 NAS matter_server.server.device_controller.[node 2][1] INFO Previous subscription failed with Error: 50, re-subscribing in 8971 ms...
2023-10-03 07:31:27 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 07:31:41 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 07:31:41 NAS chip.DMG[1] ERROR Failed to establish CASE for re-subscription with error 'src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout'
2023-10-03 07:31:41 NAS matter_server.server.device_controller.[node 2][1] INFO Previous subscription failed with Error: 50, re-subscribing in 16956 ms...
2023-10-03 07:32:31 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 07:32:45 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 07:32:45 NAS chip.DMG[1] ERROR Failed to establish CASE for re-subscription with error 'src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout'
2023-10-03 07:32:45 NAS matter_server.server.device_controller.[node 2][1] INFO Previous subscription failed with Error: 50, re-subscribing in 41359 ms...
2023-10-03 07:33:56 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 07:34:10 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 07:34:10 NAS chip.DMG[1] ERROR Failed to establish CASE for re-subscription with error 'src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout'
2023-10-03 07:34:10 NAS matter_server.server.device_controller.[node 2][1] INFO Previous subscription failed with Error: 50, re-subscribing in 70610 ms...
2023-10-03 07:35:09 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 07:35:23 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 07:35:23 NAS chip.DMG[1] ERROR Failed to establish CASE for re-subscription with error 'src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout'
2023-10-03 07:35:23 NAS matter_server.server.device_controller.[node 2][1] INFO Previous subscription failed with Error: 50, re-subscribing in 75478 ms...
2023-10-03 07:37:42 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 07:37:56 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 07:37:56 NAS chip.DMG[1] ERROR Failed to establish CASE for re-subscription with error 'src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout'
2023-10-03 07:37:56 NAS matter_server.server.device_controller.[node 2][1] INFO Previous subscription failed with Error: 50, re-subscribing in 113967 ms...
2023-10-03 07:40:34 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 07:40:48 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 07:40:48 NAS chip.DMG[1] ERROR Failed to establish CASE for re-subscription with error 'src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout'
2023-10-03 07:40:48 NAS matter_server.server.device_controller.[node 2][1] INFO Previous subscription failed with Error: 50, re-subscribing in 309396 ms...
2023-10-03 07:46:36 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 07:46:50 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 07:46:50 NAS chip.DMG[1] ERROR Failed to establish CASE for re-subscription with error 'src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout'
2023-10-03 07:46:50 NAS matter_server.server.device_controller.[node 2][1] INFO Previous subscription failed with Error: 50, re-subscribing in 261112 ms...
2023-10-03 07:50:24 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 07:50:38 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 07:50:38 NAS chip.DMG[1] ERROR Failed to establish CASE for re-subscription with error 'src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout'
2023-10-03 07:50:38 NAS matter_server.server.device_controller.[node 2][1] INFO Previous subscription failed with Error: 50, re-subscribing in 816427 ms...
2023-10-03 07:51:09 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 07:51:23 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 07:51:54 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 07:52:08 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 07:52:39 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 07:52:53 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 07:52:53 NAS matter_server.server.device_controller[1] WARNING Unable to subscribe to Node 2 as it is unavailable, will retry later in the background.
2023-10-03 08:03:24 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 08:03:38 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 08:04:09 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 08:04:23 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 08:04:54 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 08:05:08 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 08:05:08 NAS matter_server.server.device_controller[1] WARNING Unable to subscribe to Node 2 as it is unavailable, will retry later in the background.
2023-10-03 08:15:39 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 08:15:53 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 08:16:24 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 08:16:38 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 08:17:09 NAS chip.DIS[1] ERROR Timeout waiting for mDNS resolution.
2023-10-03 08:17:23 NAS chip.DIS[1] ERROR OperationalSessionSetup[1:0000000000000002]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-10-03 08:17:23 NAS matter_server.server.device_controller[1] WARNING Unable to subscribe to Node 2 as it is unavailable, will retry later in the background.
```

**Comment by marcelveldt** [comment] 2023-10-09 11:40
This is to be expected, the device can no longer be reached.
Why power it off - that is a bit the opposite of a smart device right ?

**Comment by marcelveldt** [comment] 2023-10-13 20:03
Closing this as a non-issue. Turning off a smart device will result in connection errors in the log by design and intended. Those logs do no harm at all.

**Closed by marcelveldt** 2023-10-13 20:03 UTC

**Comment by THETCR** [comment] 2023-10-20 19:20
@marcelveldt 
Trying to constantly resubscribe to a device that is offline is just a bad design pattern. 
Stating that it's a smart device and therefore should not be powered off is a non-argument.

**Comment by marcelveldt** [comment] 2023-10-20 20:46
It is a temporary measure for offline devices and can hopefully be removed soon when operational nodes discovery is fixed so we can automatically dertermine a device came back online. Also it's not subscribing at all but just polling at a low interval. Maybe calm down your tone of voice first before shouting ?
